server {
    listen 80;
    server_name localhost;
    root /usr/share/nginx/html;
    index index.html;

    # Headers de sécurité
    add_header X-Content-Type-Options "nosniff";
    add_header X-Frame-Options "DENY";
    add_header Referrer-Policy "strict-origin-when-cross-origin";
    # Autorise les images Cloudinary et ton API locale
    add_header Content-Security-Policy "default-src 'self'; script-src 'self'; style-src 'self' 'unsafe-inline'; img-src 'self' https://res.cloudinary.com; connect-src 'self' http://localhost:3001;";

    location / {
        try_files $uri $uri/ /index.html;
    }

    # Mise en cache pour maintenir le score de performance
    location ~* \.(js|css|png|jpg|jpeg|gif|ico|webp|svg)$ {
        expires 1y;
        add_header Cache-Control "public, no-transform";
    }
}