server {
    listen 80;
    server_name localhost;
    root /usr/share/nginx/html;
    index index.html;

    add_header Content-Security-Policy "default-src 'self'; 
    script-src 'self' https://upload-widget.cloudinary.com https://widget.cloudinary.com 'unsafe-inline' 'unsafe-eval'; 
    style-src 'self' 'unsafe-inline'; 
    img-src 'self' https://res.cloudinary.com data: blob:; 
    media-src 'self' https://res.cloudinary.com blob:; 
    frame-src https://upload-widget.cloudinary.com; 
    connect-src 'self' https://api.cloudinary.com https://res.cloudinary.com https://www-yonnamerlini.com;";


    location / {
        try_files $uri $uri/ /index.html;
    }

    # Mise en cache 
    location ~* \.(js|css|png|jpg|jpeg|gif|ico|webp|svg)$ {
        expires 1y;
        add_header Cache-Control "public, no-transform";
    }
}